from typing import *

from scraping import *


def explain_format():
    """Print the format of the DB file."""
    print(
        """
    Format:
    {
        f"{{market.id}}": {
        "question": f"{{market.question}}"",
        "mkt_fn": Callable = 'lambda: get_nhl_value("rangers")',
        "bet_p": float = probability of betting on the market during one run,
        "group": Optional[str] = allows grouping markets with the same outcome \
            (same string for same outcome, prepend with "!" for the complementary outcome, "not this"),
        "notes": Optional[str] = notes about the market,
    },
    ...
    }
    """
    )


# contains the market ids and the function calls to get the true probability
DB = {
    # LEAGUE
    ## Relegation, make CL, Winning
    # "4Ah1arUDDTWNMzsbyQgm": {
    #     "bet_p": 1.0,
    #     "creator": "Alex... (@AlexLiesman)",
    #     "group": None,
    #     "mkt_fn": lambda: who_higher(team_hi="Newcastle", team_lo="Tottenham Hotspur", league_name="Premier League"),
    #     "notes": None,
    #     "question": "Will Newcastle United finish the 22-23 season ABOVE Tottenham in the premier league table?",
    # },
    # "55Pyu72DmJ8cij5mBwMC": {
    #     "question": "Will Borussia Dortmund Qualify for the 2023-24 Champions League?",
    #     "mkt_fn": lambda: get_league_rel_cl_win("Borussia Dortmund", "Bundesliga", "cl"),
    #     "bet_p": 1.0,
    #     "group": None,
    #     "notes": None,
    # },
    ## Position
    # "N8ehet6R4lSuG3eLc8Zn": {
    #     "question": "Will Manchester City finish with a top 5 position in the Premier League during the 2022-2023 season?",
    #     "mkt_fn": lambda: get_league_pos("Manchester City", "Premier League", (1, 2, 3, 4, 5)),
    #     "bet_p": 0.04,
    #     "group": None,
    #     "notes": "Points deduction?",
    # },
    # "oyPzvLJhPLwKbfBrmPUL": {
    #     "question": "Will Manchester City win the Premier League?",
    #     "mkt_fn": lambda: get_league_pos("Manchester City", "Premier League", 1),
    #     "bet_p": 1.0,
    #     "group": "!arsenal_win_pl_23",
    #     "notes": None,
    # },
    # CUP
    "8Y4UL3kg1vn7EcUdhKwX": {
        "bet_p": 1.0,
        "creator": "Alex... (@AlexLiesman)",
        "group": "city_win_cl_23",
        "mkt_fn": lambda: english_team_2_oo_3(includes_all_three=True),
        "notes": "(cl, el), (cl, co), (el, co) - cl: champions league, el: europa league, co: conference league; cl: basically city, el: only utd, co: only west ham",
        "question": "Will Premier League teams win 2 of the Champions League, Europa League, or Conference League this year?",
    },
    "6lhf7NU7wtIkJJ30xohK": {
        "question": "Sport 2023: Will Manchester City win the UEFA Champions League?",
        "mkt_fn": lambda: get_cup_stage("Manchester City", "Champions League", "win"),
        "bet_p": 1.0,
        "group": "city_win_cl_23",
        "notes": None,
    },
    "tU1f2izprX2HHsXfMFRE": {
        "bet_p": 1.0,
        "creator": "firstuserhere (@firstuserhere)",
        "mkt_fn": lambda: get_cup_stage("Manchester City", "Champions League", "win"),
        "group": "city_win_cl_23",
        "notes": None,
        "question": "UEFA Champions League Finals: Manchester city vs Inter Milan",
    },
    "JGSaFciZSDfc7SVCg4sz": {
        "bet_p": 1.0,
        "creator": "Lawson Clark (@LawsonClark)",
        "mkt_fn": lambda: get_cup_stage("Manchester City", "Champions League", "win"),
        "group": "city_win_cl_23",
        "notes": None,
        "question": "soccer: will man city win the UEFA champions league final",
    },
    "quiVjRGIOVRbHraRXQar": {
        "bet_p": 1.0,
        "creator": "NamesAreHard (@NamesAreHard)",
        "group": "!city_win_cl_23",
        "mkt_fn": lambda: get_cup_stage("Internazionale", "Champions League", "win"),
        "notes": None,
        "question": "Will Inter win the 2022-2023 UEFA Champions League?",
    },
    # NBA
    # "f27xC1Sp6wHyeQwICaPA": {
    #     "question": "Sport 2023: Memphis Grizzlies win NBA finals?",
    #     "mkt_fn": lambda: get_nba_value("MEM", "win_finals"),
    #     "bet_p": 0.0,
    #     "group": "mem_win_nba_23",
    #     "notes": None,
    # },
    # "jLTGa4ceWzDwSjtzIqio": {
    #     "bet_p": 1.0,
    #     "creator": "Ron Wiener (@RonWiener)",
    #     "group": None,
    #     "mkt_fn": lambda: (
    #         print("NB: KD Finals MVP = PHX champs * 1.1 (PHX boost) * 0.74 (KD chosen)"),
    #         get_nba_value("PHX", "win_finals") * 1.1 * 0.74,
    #     )[1],
    #     "notes": "dangerous but should be OK",
    #     "question": "Will Kevin Durant Win 2023 NBA Finals MVP?",
    # },
    "4vxelGioWyP8OP9GF4CV": {
        "question": "Which team will win the 2022-23 NBA Championship? (Los Angeles Clippers)",
        "mkt_fn": lambda: get_nba_value("LAC", "win_finals"),
        "bet_p": 0.0,
        "group": "lac_win_nba_23",
        "notes": None,
    },
    "58XTZb0Eby9JOVcZ1NvM": {
        "question": "Which team will win the 2022-23 NBA Championship? (Phoenix Suns)",
        "mkt_fn": lambda: get_nba_value("PHX", "win_finals"),
        "bet_p": 1.0,
        "group": "phx_win_nba_23",
        "notes": None,
    },
    "PP3i3jMSGN02KOBu7KPy": {
        "question": "Which team will win the 2022-23 NBA Championship? (Sacramento Kings)",
        "mkt_fn": lambda: get_nba_value("SAC", "win_finals"),
        "bet_p": 1.0,
        "group": "sac_win_nba_23",
        "notes": None,
    },
    # "oIaenjHLTjj5QKfjYYzN": {
    #     "question": "Which team will win the 2022-23 NBA Championship? (Memphis Grizzlies)",
    #     "mkt_fn": lambda: get_nba_value("MEM", "win_finals"),
    #     "bet_p": 0.0,
    #     "group": "mem_win_nba_23",
    #     "notes": None,
    # },
    "3Pe7pYrPLwg3ascu2as2": {
        "question": "Which team will win the 2022-23 NBA Championship? (New York Knicks)",
        "mkt_fn": lambda: get_nba_value("NY", "win_finals"),
        "bet_p": 1.0,
        "group": "knicks_win_nba_23",
        "notes": None,
    },
    "RTrAMmuvhkkWHLPe5y1k": {
        "question": "Which team will win the 2022-23 NBA Championship? (Philadelphia 76ers)",
        "mkt_fn": lambda: get_nba_value("PHI", "win_finals"),
        "bet_p": 1.0,
        "group": "phi_win_nba_23",
        "notes": None,
    },
    # "CkW1U170p1Ur1kWpdjFh": {
    #     "question": "Which team will win the 2022-23 NBA Championship? (Milwaukee Bucks)",
    #     "mkt_fn": lambda: get_nba_value("MIL", "win_finals"),
    #     "bet_p": 0.0,
    #     "group": "mil_win_nba_23",
    #     "notes": None,
    # },
    "FcRHGUXF8fxMkZUROtdo": {
        "question": "Which team will win the 2022-23 NBA Championship? (Denver Nuggets)",
        "mkt_fn": lambda: get_nba_value("DEN", "win_finals"),
        "bet_p": 1.0,
        "group": "den_win_nba_23",
        "notes": None,
    },
    ## NBA prognostic8r
    "Ya4sAjQ1gdFIGnH4vYg5": {
        "question": "Will the Brooklyn Nets make the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: 0,
        "bet_p": 1.0,
        "group": None,
        "notes": None,
    },
    "Nwl8UgIDTdBjtQpRwMsq": {
        "question": "Will the Miami Heat make the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: get_nba_value("MIA", "make_finals"),
        "bet_p": 1.0,
        "group": "!bos_make_finals_23",
        "notes": None,
    },
    "zDa6klhG9DSaB2oyNG8P": {
        "question": "Will the New Orleans Pelicans make the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: get_nba_value("NO", "make_finals"),
        "bet_p": 1.0,
        "group": None,
        "notes": None,
    },
    "dchxiQkTEn0BRdsz3kKf": {
        "question": "Will the Denver Nuggets make the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: get_nba_value("DEN", "make_finals"),
        "bet_p": 1.0,
        "group": "den_make_finals_23",
        "notes": None,
    },
    "tditUf6BhjpDRYblEOe6": {
        "question": "Will the Golden State Warriors make the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: get_nba_value("GS", "make_finals"),
        "bet_p": 1.0,
        "group": None,
        "notes": None,
    },
    "83hh8sbz6CzU9CZvZrM5": {
        "question": "Will the Philadelphia 76ers make the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: get_nba_value("PHI", "make_finals"),
        "bet_p": 1.0,
        "group": None,
        "notes": None,
    },
    # "zMn3jPsvG1MqJNSzjqcB": {
    #     "question": "Will the Milwaukee Bucks make the finals in the 2022-2023 NBA season?",
    #     "mkt_fn": lambda: get_nba_value("MIL", "make_finals"),
    #     "bet_p": 0.0,
    #     "group": "mil_make_finals_23",
    #     "notes": None,
    # },
    # # "0Zr3UwcrkRbYUBMlG1BS": {
    #     "question": "Will the Memphis Grizzlies make the finals in the 2022-2023 NBA season?",
    #     "mkt_fn": lambda: get_nba_value("MEM", "make_finals"),
    #     "bet_p": 0.0,
    #     "group": None,
    #     "notes": None,
    # },
    "Scfdsvw22nbnz5HKj0nx": {
        "question": "Will the Miami Heat win the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: get_nba_value("MIA", "win_finals"),
        "bet_p": 1.0,
        "group": "!den_win_nba_23",
        "notes": None,
    },
    "EAt51eS8hcW6h9xcYFSQ": {
        "question": "Will the Denver Nuggets win the finals in the 2022-2023 NBA season?",
        "mkt_fn": lambda: get_nba_value("DEN", "win_finals"),
        "bet_p": 1.0,
        "group": "den_win_nba_23",
        "notes": None,
    },
    "VRjuGH2n6abm4jwT821f": {
        "bet_p": 1.0,
        "creator": "Kevin Burke (@KevinBurke)",
        "mkt_fn": lambda: get_nba_value("DEN", "win_finals"),
        "group": "den_win_nba_23",
        "notes": None,
        "question": "Will the Denver Nuggets win the 2023 NBA Finals vs. the Miami Heat?",
    },
    "fJWiC7xeEaLrJBqSppjF": {
        "bet_p": 1.0,
        "creator": "RJ Perez (@RJPerez)",
        "mkt_fn": lambda: get_nba_value("DEN", "win_finals"),
        "group": "den_win_nba_23",
        "notes": None,
        "question": "Will the #1 Denver Nuggets win the 2023 NBA Finals against the #8 Miami Heat?",
    },
    ## NBA RJ Perez
    # "H20g2iyc6WxoQUtBKeWd": {
    #     "bet_p": 1.0,
    #     "creator": "RJ Perez (@RJPerez)",
    #     "group": None,  # "seed_1_2_upset_23",
    #     "mkt_fn": seed_1_2_upset_23,
    #     "notes": None,
    #     "question": "Will a 1 or 2 seed lose in the First Round of the 2023 NBA Playoffs?",
    # },
    # "VIvblNLoAguyvLKRHJDY": {
    #     "bet_p": 0.64,
    #     "creator": "RJ Perez (@RJPerez)",
    #     "group": None,  # "seed_1_2_upset_23",
    #     "mkt_fn": lambda: (print("NB: at least 3 wins (change if getting close) = upset seed 1 or 2 * 1.04"), seed_1_2_upset_23() * 1.04)[1],
    #     "notes": "must be higher than the one above",
    #     "question": "Will a play-in team win at least 3 games in the First Round of the 2023 NBA Playoffs?",
    # },
    # NHL
    "RrqB3uQAIMzBrXTAxjfC": {
        "question": "Sport 2023: Boston Bruins win Stanley Cup?",
        "mkt_fn": lambda: get_nhl_value("bruins"),
        "bet_p": 1.0,
        "group": "bruins_nhl_23",
        "notes": None,
    },
    "YxRPgMjXuT4ywJyOi6Qr": {
        "question": "Will the Carolina Hurricanes win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("hurricanes"),
        "bet_p": 1.0,
        "group": "hurricanes_nhl_23",
        "notes": None,
    },
    "1SmjLoF1tmKlG5VTGvrH": {
        "question": "Will the Florida Panthers win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("panthers"),
        "bet_p": 1.0,
        "group": "panthers_nhl_23",
        "notes": None,
    },
    "orpXgAGQDhQjvX231Czg": {
        "question": "Will the St Louis Blues win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("blues"),
        "bet_p": 1.0,
        "group": None,
        "notes": None,
    },
    "314VvYjyMdngNUpRP4FD": {
        "question": "Will the Calgary Flames win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("flames"),
        "bet_p": 1.0,
        "group": None,
        "notes": None,
    },
    "OLxeooyTtTZz89mfEQ66": {
        "question": "Will the Edmonton Oilers win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("oilers"),
        "bet_p": 1.0,
        "group": "oilers_nhl_23",
        "notes": None,
    },
    "aFy7zThA1GmCKU9g4Dcz": {
        "question": "Will the New York Rangers win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("rangers"),
        "bet_p": 1.0,
        "group": "rangers_nhl_23",
        "notes": None,
    },
    "By0jcsXwHaHGZU5TSpkU": {
        "question": "Will the Tampa Bay Lightning win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("lightning"),
        "bet_p": 1.0,
        "group": "lightning_nhl_23",
        "notes": None,
    },
    "a9g7yrxY6liv1hH199cy": {
        "question": "Will the Colorado Avalanche win the 2023 NHL playoffs?",
        "mkt_fn": lambda: get_nhl_value("avalanche"),
        "bet_p": 1.0,
        "group": "avalanche_nhl_23",
        "notes": None,
    },
    "18biGCtj53LHkwJp3o6B": {
        "question": "Sport 2023: Will Colorado Avalanche win Stanley Cup?",
        "mkt_fn": lambda: get_nhl_value("avalanche"),
        "bet_p": 1.0,
        "group": "avalanche_nhl_23",
        "notes": None,
    },
    "8Mj04iexbWtgljdsOTtj": {
        "question": "Will the Colorado Avalanche make the 2023 NHL Playoffs?",
        "mkt_fn": None,
        "bet_p": 0.0,
        "group": None,
        "notes": "don't have a market function for nhl playoffs yet",
    },
    "2BoLdf6dtDUW9iOG7cn8": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": "bruins_nhl_23",
        "mkt_fn": lambda: get_nhl_value("bruins"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Boston Bruins)",
    },
    "GbGRrmGoRynPtm5HxnIl": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": "lightning_nhl_23",
        "mkt_fn": lambda: get_nhl_value("lightning"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Tampa Bay Lightning)",
    },
    "NVlWNWGb0SHsAJekw8jt": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": None,
        "mkt_fn": lambda: get_nhl_value("stars"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Dallas Stars)",
    },
    "OWkM9xZioIKKeG5RZjlX": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": "panthers_nhl_23",
        "mkt_fn": lambda: get_nhl_value("panthers"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Florida Panthers)",
    },
    "RedYiZuBYNG5lEt8JD0B": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": "rangers_nhl_23",
        "mkt_fn": lambda: get_nhl_value("rangers"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (NY Rangers)",
    },
    "X419cOOU8VPkY3En6772": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": None,
        "mkt_fn": lambda: get_nhl_value("devils"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (New Jersey Devils)",
    },
    "YFc4fxF4paTLXRFsuRrM": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": None,
        "mkt_fn": lambda: get_nhl_value("golden-knights"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Vegas Golden Knights)",
    },
    "Z1XjCUAUTyXb18ZZ05nS": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": None,
        "mkt_fn": lambda: get_nhl_value("maple-leafs"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Toronto Maple Leafs)",
    },
    "an3IXMniFSZax4FxhxuD": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": "hurricanes_nhl_23",
        "mkt_fn": lambda: get_nhl_value("hurricanes"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Carolina Hurricanes)",
    },
    "aoiF95ZL8Nf4P4yCwEki": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": "oilers_nhl_23",
        "mkt_fn": lambda: get_nhl_value("oilers"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Edmonton Oilers)",
    },
    "icr5LRwLbTObfE8TLcyK": {
        "bet_p": 1.0,
        "creator": "Metaculus Bot (@MetaculusBot)",
        "group": None,
        "mkt_fn": lambda: get_nhl_value("wild"),
        "notes": None,
        "question": "Which NHL team will win the 2022-23 Stanley Cup? (Minnesota Wild)",
    },
    ## Misc
    "xN0Y9t6LnEKtQ7UnuHli": {
        "bet_p": 1.0,
        "creator": "Kevin Burke (@KevinBurke)",
        "group": None,
        "mkt_fn": lambda: get_cup_stage("San Jose Earthquakes", "MLS", "make_playoffs"),
        "notes": None,
        "question": "Will the San Jose Earthquakes qualify for the 2023 MLS Cup playoffs?",
    },
    "zSe8OSeGe6pqshWpgGl7": {
        "bet_p": 1.0,
        "creator": "Kevin Burke (@KevinBurke)",
        "group": None,
        "mkt_fn": lambda: get_cup_stage("St. Louis CITY SC", "MLS", "make_playoffs"),
        "notes": None,
        "question": "Will St. Louis City SC qualify for the MLS Cup Playoffs?",
    },
    "h1dRqAYoHqUoLVud36iL": {
        "bet_p": 1.0,
        "creator": "Alex... (@AlexLiesman)",
        "group": None,
        "mkt_fn": lambda: get_nhl_value("oilers") + get_nhl_value("maple-leafs"),
        "notes": None,
        "question": "Will a team from Canada win the Stanley Cup in 22-23 the season?",
    },
    "vizWqRI9wTPR9hOGCBUx": {
        "bet_p": 1.0,
        "creator": "Spongpad (@LBeesley)",
        "group": None,
        "mkt_fn": lambda: 1 - (1 - get_nhl_value("oilers", "make_conf_final")) * (1 - get_nhl_value("maple-leafs", "make_conf_final")),
        "notes": None,
        "question": "Will a Canadian NHL team advance to the conference finals of the Stanley Cup playoff?",
    },
    "7sRw3ZDd8ESyk1Gm1dgO": {
        "bet_p": 1.0,
        "creator": "Heliscone (@Heliscone)",
        "group": "panthers_beat_hurricanes_23",
        "mkt_fn": lambda: get_nhl_value("panthers", "make_final"),
        "notes": None,
        "question": "Will the Panthers beat the Canes? (2023 NHL ECF)",
    },
    "zFnxIJu42a2R24cJBr6d": {
        "bet_p": 1.0,
        "creator": "Heliscone (@Heliscone)",
        "group": "stars_beat_knights_23",
        "mkt_fn": lambda: get_nhl_value("stars", "make_final"),
        "notes": None,
        "question": "Will the Stars beat the Knights? (2023 NHL WCF)",
    },
    "fBqhqPELuNeNMAeiRTX2": {
        "bet_p": 1.0,
        "creator": "BossM3dusa (@MAXMcCoy)",
        "group": "panthers_nhl_23",
        "mkt_fn": lambda: get_nhl_value("panthers"),
        "notes": None,
        "question": "Will the Panthers win the Stanley Cup.",
    },
}


IDENTICAL_MARKETS = {
    "Z0VFA6IdkKF82hRErzp7": {
        "bet_p": 1.0,
        "creator": "prognostic8r (@prognostic8r)",
        "group": "jokic_mvp_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Nikola Jokić win the Most Valuable Player award for the 2022-2023 NBA season?",
    },
    "lTi5OmPcHZje9iCxqUUB": {
        "bet_p": 1.0,
        "creator": "Benjamin Hemming (@BenjaminHemming)",
        "group": "jokic_mvp_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Nikola Jokic win a third straight MVP this season?",
    },
    "BsM6rDyUkG2WVc1UHa3L": {
        "bet_p": 0.0,
        "creator": "Ron Wiener (@RonWiener)",
        "group": "nba_sweep_1st_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will any 1st round NBA series end in a sweep?",
    },
    "Y4Zg37TwMYfm6Vh6zUJ7": {
        "bet_p": 0.0,
        "creator": "Alex... (@AlexLiesman)",
        "group": "nba_sweep_1st_23",
        "mkt_fn": None,
        "notes": None,
        "question": "NBA playoffs: Will any team get swept in the first round?",
    },
    "3TXOeuBWsEYb86yUFB5A": {
        "bet_p": 1.0,
        "creator": "Roberto Brix Mallari (@BrixMallari)",
        "group": "giannis_mvp_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Giannis Antetokoumpo be the Kia Mvp?",
    },
    "EIoVX5TJYNlMiCKqCy0W": {
        "bet_p": 1.0,
        "creator": "prognostic8r (@prognostic8r)",
        "group": "giannis_mvp_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Giannis Antetokounmpo win the Most Valuable Player award for the 2022-2023 NBA season?",
    },
    # "VMfDQ5BKrXGkL2roZmQn": {
    #     "bet_p": 1.0,
    #     "creator": "swiftieforever (@swiftielover)",
    #     "group": "levi_pretty",
    #     "mkt_fn": None,
    #     "notes": None,
    #     "question": 'Will the "am i pretty" market resolve ' "YES?",
    # },
    # "6caU1Z2qBNtNdmhkAu1y": {
    #     "bet_p": 1.0,
    #     "creator": "levina finkelstein (@levifinkelstein)",
    #     "group": "levi_pretty",
    #     "mkt_fn": None,
    #     "notes": None,
    #     "question": "Am I pretty? 🥺 People always call me ugly 😔 😞  ----------   (resolves like " '"the market")',
    # },
    # "GJTLnS8ItArmLg6tZF6z": {
    #     "bet_p": 1.0,
    #     "creator": "CodeandSolder (@CodeandSolder)",
    #     "group": "!whales_vs_minnows",
    #     "mkt_fn": None,
    #     "notes": None,
    #     "question": "[Anti-Whale Aktion] Will Isaac King's Whales vs Minnows market resolve no?",
    # },
    # "U3zLgOZkGUE7cvG98961": {
    #     "bet_p": 0.0,
    #     "creator": "Isaac King (@IsaacKing)",
    #     "group": "whales_vs_minnows",
    #     "mkt_fn": None,
    #     "notes": None,
    #     "question": "Whales vs. Minnows: Will traders hold at least 10000x as many YES shares as there are traders holding NO shares?",
    # },
    # "EfnZXB5sNG9ixcfuw8xx": {
    #     "bet_p": 1.0,
    #     "creator": "Dreamingpast (@Dreamingpast)",
    #     "group": "whales_vs_minnows",
    #     "mkt_fn": None,
    #     "notes": None,
    #     "question": "What will be the final closing % of WvM?",
    # },
    # "vJ4QYaOfNdxbhAXcCRPa": {
    #     "bet_p": 0.0,
    #     "creator": "Zorn (@Zorn)",
    #     "group": "whales_vs_minnows",
    #     "mkt_fn": None,
    #     "notes": None,
    #     "question": "Will the Whales vs. Minnows Market Resolves to Yes?",
    # },
    "64y6rYJ65TuiRqkkSuyf": {
        "bet_p": 1.0,
        "creator": "Tom Cohen (@TomCohen)",
        "group": "tom_cohen_yes",
        "mkt_fn": None,
        "notes": None,
        "question": "Will I be convinced to resolve this market Yes?",
    },
    "Av8WTpcV5dV7ZJdQzhH2": {
        "bet_p": 1.0,
        "creator": "John Smith (@JohnSmithb9be)",
        "group": "tom_cohen_yes",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Tom Cohen be convinced to resolve this market Yes?",
    },
    "P9kIYDOqTmiFTJXmwzUr": {
        "bet_p": 1.0,
        "creator": "Ammon Lam (@AmmonLam)",
        "group": "trump_wins_24_election",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Donald Trump win the 2024 US presidential election?",
    },
    "SsAdHNNaI9hRRMe1XqgG": {
        "bet_p": 1.0,
        "creator": "crystal ball (@duck)",
        "group": "trump_wins_24_election",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Donald Trump win the 2024 presidential election?",
    },
    "Ua0kzjbcBjwSySES4hYt": {
        "bet_p": 1.0,
        "creator": "Lars Doucet (@LarsDoucet)",
        "group": "trump_wins_24_election",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Donald Trump win the 2024 US Presidential Election?",
    },
    "lk0fi7Cd28d1oy0w28hz": {
        "bet_p": 1.0,
        "creator": "sushi P wizard (@rush)",
        "group": "trump_wins_24_election",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Donald Trump win the 2024 Election?",
    },
    "SaYAfc0m7RagwgaeapFJ": {
        "bet_p": 1.0,
        "creator": "divij goyal (@divijgoyal)",
        "group": "trump_wins_24_election",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Trump win 2024 elections?",
    },
    "4amdGgZFKTxUMC3Fym6F": {
        "bet_p": 1.0,
        "creator": "Lars Doucet (@LarsDoucet)",
        "group": "biden_wins_24_election",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Joe Biden win the 2024 US Presidential Election?",
    },
    "JAi0Fme4Evjo8542ArS2": {
        "bet_p": 1.0,
        "creator": "Ammon Lam (@AmmonLam)",
        "group": "biden_wins_24_election",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Joe Biden win the 2024 US presidential election?",
    },
    "R9ywbZdVqmhJpxpU70xs": {
        "bet_p": 1.0,
        "creator": "ACX Bot (@ACXBot)",
        "group": "trump_tweets_23",
        "mkt_fn": None,
        "notes": None,
        "question": "21. Will Donald Trump make at least one tweet in 2023?",
    },
    "f7ILZzgjkTpYuHwdhHY2": {
        "bet_p": 1.0,
        "creator": "metabro (@metabro)",
        "group": "trump_tweets_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Donald Trump's return on Twitter:  Will @realDonaldTrump tweet in 2023?",
    },
    "usSjx2AtbUvfg7QNq5g2": {
        "bet_p": 1.0,
        "creator": "Tomek K 🟡 (@itsTomekK)",
        "group": "trump_tweets_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Donald Trump's return on Twitter:  Will @realDonaldTrump tweet in 2023?",
    },
    "6Mbxuu6YkcvC2NmvUcBJ": {
        "bet_p": 1.0,
        "creator": "S G (@SG)",
        "group": "desantis_nom_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Ron DeSantis be the 2024 Republican presidential nominee?",
    },
    "gcYnnl4R2A0yBp0ARFM7": {
        "bet_p": 1.0,
        "creator": "Jack (@jack)",
        "group": "desantis_nom_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Ron DeSantis be the 2024 Republican nominee for president?",
    },
    "v2B2bNMKHeFikYqwZ4w6": {
        "bet_p": 1.0,
        "creator": "Embedded Agent (@EA42)",
        "group": "desantis_nom_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Ron DeSantis be the Republican 2024 nominee?",
    },
    "3K63FYyhwljHyac11tXy": {
        "bet_p": 1.0,
        "creator": "Jim (@JimAusman)",
        "group": "youngkin_nom_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Virginia Governor Glenn Youngkin be the Republican Party nominee for President in 2024 in the general election.",
    },
    "SMMblDKhRMEc28PBNJ23": {
        "bet_p": 1.0,
        "creator": "Brian T. Edwards (@BTE)",
        "group": "youngkin_run_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Glenn Youngkin run for president in 2024?",
    },
    "ykCs0oLIFrR8NtSXa85f": {
        "bet_p": 1.0,
        "creator": "Jim (@JimAusman)",
        "group": "youngkin_run_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Virginia Governor Glenn Youngkin run for President of the United States in 2024 election.",
    },
    "wDQKfGCMxBi7zev3zEXQ": {
        "bet_p": 1.0,
        "creator": "Jack (@jack)",
        "group": "youngkin_nom_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Glenn Youngkin be the 2024 Republican nominee for president?",
    },
    "PIWAZrAN9NSIYLrrwBDB": {
        "bet_p": 1.0,
        "creator": "brwa (@brwa)",
        "group": "us_gov_shutdown_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will there be a government shutdown in the US in 2023?",
    },
    "skOczsGCpLFvjjsxqvWm": {
        "bet_p": 1.0,
        "creator": "connorcash (@connorcash)",
        "group": "us_gov_shutdown_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will there be a US government shutdown before the end of 2023?",
    },
    "xZAZGWRxpC5dpCpYPUnu": {
        "bet_p": 1.0,
        "creator": "Nostradamnedus (@Nostradamnedus)",
        "group": "us_gov_shutdown_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will there be a US Government shutdown during 2023?",
    },
    "2ZxO9lmrBy76JrxtvDBg": {
        "bet_p": 1.0,
        "creator": "Gigacasting (@Gigacasting)",
        "group": "pence_nom_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Mike Pence be the Republican nominee?",
    },
    "7DmMDRYV47OK9oiwaSkr": {
        "bet_p": 1.0,
        "creator": "N.C. Young (@NcyRocks)",
        "group": "pence_run_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Mike Pence run for President in 2024?",
    },
    "DFCmfW1IoFEEP5kmaLmp": {
        "bet_p": 1.0,
        "creator": "BRTD (@BRTD)",
        "group": "pence_run_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Mike Pence run for President in 2024?",
    },
    "V6I5sjlmSoVPhDc4xdK9": {
        "bet_p": 1.0,
        "creator": "Jack (@jack)",
        "group": "pence_nom_24",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Mike Pence be the 2024 Republican nominee for president?",
    },
    "vSggBCnqpLfjzpKHQsg4": {
        "bet_p": 1.0,
        "creator": "Tomek K 🟡 (@itsTomekK)",
        "group": "pence_run_24",
        "mkt_fn": None,
        "notes": None,
        "question": "American politics 2023: Mike Pence runs for president?",
    },
    "G0krb608arXZlJq3Pu3E": {
        "bet_p": 1.0,
        "creator": "Tomek K 🟡 (@itsTomekK)",
        "group": "!biden_impeach_23",
        "mkt_fn": None,
        "notes": None,
        "question": "American politics 2023: Joe Biden is not impeached?",
    },
    "xa1I62Ax33De66nvEUx5": {
        "bet_p": 1.0,
        "creator": "Gigacasting (@Gigacasting)",
        "group": "biden_impeach_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will Biden be impeached in 2023?",
    },
    "5F6J85qsunXCHPfYKM0O": {
        "bet_p": 1.0,
        "creator": "RJ Perez (@RJPerez)",
        "group": "den_mia_gm6_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the #1 Denver Nuggets win Game 6 of the 2023 NBA Finals against the #8 Miami Heat?",
    },
    "E74JGx67k3zoxUFenwZn": {
        "bet_p": 1.0,
        "creator": "RJ Perez (@RJPerez)",
        "group": "den_mia_gm4_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the #1 Denver Nuggets win Game 4 of the 2023 NBA Finals against the #8 Miami Heat?",
    },
    "Gp9v2eEmXP3FaEEDa26h": {
        "bet_p": 1.0,
        "creator": "Kevin Burke (@KevinBurke)",
        "group": "den_mia_gm7_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the Denver Nuggets win Game 7 of the 2023 NBA Finals vs. the Miami Heat?",
    },
    "RNcM5NZjeRxZTRvJTrmv": {
        "bet_p": 1.0,
        "creator": "Kevin Burke (@KevinBurke)",
        "group": "den_mia_gm4_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the Denver Nuggets win Game 4 of the 2023 NBA Finals vs. the Miami Heat?",
    },
    "VcBUQ2J2res8KhYeVckS": {
        "bet_p": 1.0,
        "creator": "Kevin Burke (@KevinBurke)",
        "group": "den_mia_gm5_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the Denver Nuggets win Game 5 of the 2023 NBA Finals vs. the Miami Heat?",
    },
    "WtDcSmbPZuaz0MQaUoFO": {
        "bet_p": 1.0,
        "creator": "RJ Perez (@RJPerez)",
        "group": "den_mia_gm7_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the #1 Denver Nuggets win Game 7 of the 2023 NBA Finals against the #8 Miami Heat?",
    },
    "fOChLWgwpKBXQelNRg7z": {
        "bet_p": 1.0,
        "creator": "Kevin Burke (@KevinBurke)",
        "group": "den_mia_gm6_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the Denver Nuggets win Game 6 of the 2023 NBA Finals vs. the Miami Heat?",
    },
    "kCDtb2PyAF5SXdPxbZRY": {
        "bet_p": 1.0,
        "creator": "RJ Perez (@RJPerez)",
        "group": "den_mia_gm5_23",
        "mkt_fn": None,
        "notes": None,
        "question": "Will the #1 Denver Nuggets win Game 5 of the 2023 NBA Finals against the #8 Miami Heat?",
    },
}
